library(lubridate)
df <- read.csv("household_power_consumption.txt", sep = ";", na.strings="?", stringsAsFactors=FALSE)
df <- subset(df, (Date == "1/2/2007") | (Date == "2/2/2007"))
df$DateTime <- dmy_hms(paste(df$Date,df$Time))

Sys.setlocale("LC_ALL", "English") 
plot(df$DateTime, df$Sub_metering_1, type="n", main = "", xlab="", ylab="Energy sub metering")
lines(df$DateTime, df$Sub_metering_1, type="l", col="black")
lines(df$DateTime, df$Sub_metering_2, type="l", col="red") 
lines(df$DateTime, df$Sub_metering_3, type="l", col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))